image:
  repository: nvcr.io/nvidia/nemo
  tag: 24.12-rc0

service:
  type: ClusterIP
  port: 8888

resources:
  limits:
    cpu: 1
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

persistence:
  enabled: true
  size: 10Gi
  storageClass: ""
  existingClaim: ""

config:
  password: ""
  allowRoot: false

command:
  enabled: true
  entrypoint: ["/bin/bash", "-c"]
  args:
    [
      "apt update && apt install graphviz -y && jupyter lab --ServerApp.ip=0.0.0.0 --ServerApp.port=8888 --ServerApp.allow_root=True --no-browser",
    ]
