apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-files
  labels:
    app: {{ .Release.Name }}
    {{- include "k8s-hello-world.labels" . | nindent 4 }}
data:
  {{- $files := .Files }}
  {{- range $path, $_ :=  .Files.Glob "files/**" }}
  {{ trimPrefix "files/" $path | replace "/" "." }}: |-
    {{- $files.Get $path | nindent 4 }}
  {{- end }}
