apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-k8s-hello-world
  labels:
    {{- include "k8s-hello-world.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "k8s-hello-world.selectorLabels" . | nindent 4 }}
